# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/chat_multicast.rb'

Hoe.new('ChatMulticast', ChatMulticast::VERSION) do |p|
  p.developer('Matthew Anderson', 'manderson@onehub.com')
end

# vim: syntax=Ruby
