# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/chat_multicast.rb'

Hoe.new('ChatMulticast', Chatmulticast::VERSION) do |p|
  # p.rubyforge_name = 'ChatMulticastx' # if different than lowercase project name
  # p.developer('FIX', 'FIX@example.com')
end

# vim: syntax=Ruby
